var kyivMaps = `<div id='g-kyiv-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 16:14 -->
	<!-- ai file: kyiv -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-kyiv-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='950'>
		<style type='text/css' media='screen,print'>
			#g-kyiv-Artboard_1{
				position:relative;
				overflow:hidden;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-kyiv-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle0 {
				font-size:21px;
				line-height:25px;
				text-align:center;
				color:#3a3f4a;
				font-weight: bold;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle1 {
				font-size:14px;
				line-height:17px;
				color:#C2C2C2;
				font-weight:#300;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#3a3f4a;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle4 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
				font-weight: bold;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle5 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle6 {
				font-size:10px;
				line-height:14px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle7 {
				font-size:10px;
				line-height:12px;
				color:#999999;
			}
			#g-kyiv-Artboard_1 .g-aiPstyle8 {
				font-size:10px;
				line-height:12px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-kyiv-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/kyiv-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:3.162%;left:78.8177%;width:50.5819%;margin-left:-25.291%;'>
				<p class='g-aiPstyle0'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:3.162%;left:23.7297%;width:50.5819%;margin-left:-25.2909%;'>
				<p class='g-aiPstyle0'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:4.3917%;left:0.2719%;width:7.6241%;'>
				<p class='g-aiPstyle1'>КИЇВ</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:8.4321%;left:23.4011%;width:37.8078%;margin-left:-18.9039%;'>
				<p class='g-aiPstyle2'>(середнє значення за 13 та 29 липня 2016 року,</p>
				<p class='g-aiPstyle2'>30 м на піксель)</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:8.4321%;left:78.6997%;width:57.3026%;margin-left:-28.6513%;'>
				<p class='g-aiPstyle2'>(середнє значення за 13 та 29 липня 2016 року,</p>
				<p class='g-aiPstyle2'>100 м на піксель)</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:58.4974%;left:57.7756%;width:8.8435%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Оболоні</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:60.9568%;left:0.4499%;width:15.9344%;'>
				<p class='g-aiPstyle3'>NDVI (Нормалізований відносний індекс рослинності) &mdash; показник кількості активної фотосинтетичної  біомаси </p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:72.7265%;left:88.0086%;width:9.82%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Позняках, Березняках і Воскресенці</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:77.9966%;left:10.6792%;width:8.0503%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:77.9966%;left:62.7785%;width:11.7688%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:80.9829%;left:3.3984%;width:8.0475%;'>
				<p class='g-aiPstyle5'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:81.1586%;right:30.2464%;width:3.7668%;'>
				<p class='g-aiPstyle6'>23,7</p>
				<p class='g-aiPstyle6'>27,0</p>
				<p class='g-aiPstyle6'>30,4</p>
				<p class='g-aiPstyle6'>34,8</p>
				<p class='g-aiPstyle6'>40,1</p>
				<p class='g-aiPstyle6'>45,5</p>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:81.1586%;right:84.921%;width:3.7536%;'>
				<p class='g-aiPstyle6'>0,93</p>
				<p class='g-aiPstyle6'>0,73</p>
				<p class='g-aiPstyle6'>0,52</p>
				<p class='g-aiPstyle6'>0,32</p>
				<p class='g-aiPstyle6'>0,16</p>
				<p class='g-aiPstyle6'>-0,09</p>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:93.631%;left:96.5714%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:96.039%;right:0.3099%;width:27.5678%;'>
				<p class='g-aiPstyle8'>Дані: Landsat 8, OpenStreetMap</p>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 16:14 -->
</div>`




var odesaMaps = `<div id='g-odesa-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-01 - 21:25 -->
	<!-- ai file: odesa -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-odesa-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='950'>
		<style type='text/css' media='screen,print'>
			#g-odesa-Artboard_1{
				position:relative;
				overflow:hidden;
				width:950px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-odesa-Artboard_1 p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-odesa-Artboard_1 .g-aiPstyle0 {
				font-size:21px;
				line-height:25px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-odesa-Artboard_1 .g-aiPstyle1 {
				font-size:14px;
				line-height:17px;
				color:#C2C2C2;
				font-weight: 300;
			}
			#g-odesa-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				text-align:center;
				color:#3a3f4a;
				font-weight: 300;
			}
			#g-odesa-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#3a3f4a;
			}
			#g-odesa-Artboard_1 .g-aiPstyle4 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-odesa-Artboard_1 .g-aiPstyle5 {
				font-size:11px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-odesa-Artboard_1 .g-aiPstyle6 {
				font-size:10px;
				line-height:13px;
				color:#3a3f4a;
				text-align:right;
			}
			#g-odesa-Artboard_1 .g-aiPstyle7 {
				font-size:10px;
				line-height:12px;
				color:#999999;
			}
			#g-odesa-Artboard_1 .g-aiPstyle8 {
				font-size:10px;
				line-height:12px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-odesa-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/odesa-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:3.8441%;left:79.4378%;width:35.1579%;margin-left:-17.5789%;'>
				<p class='g-aiPstyle0'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:4.0188%;left:25.323%;width:36.4402%;margin-left:-18.2201%;'>
				<p class='g-aiPstyle0'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:4.8925%;left:0.3158%;width:7.6241%;'>
				<div class='g-aiPstyle1'>ОДЕСА</div>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:8.9114%;left:25.4711%;width:38.1718%;margin-left:-19.0859%;'>
				<div class='g-aiPstyle2'>(середнє значення за 20 липня та 5 серпня 2015 року, 30 м на піксель)</div>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:8.9114%;left:80.3708%;width:37.0238%;margin-left:-18.5119%;'>
				<div class='g-aiPstyle2'>(середнє значення за 20 липня та 5 серпня 2015 року, 100 м на піксель)</div>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:23.4142%;left:69.6872%;width:10.2769%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки у Суворовському районі</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:39.839%;left:5.1294%;width:11.5762%;'>
				<p class='g-aiPstyle3'>Преображенський парк в центрі міста</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:41.7611%;left:88.0595%;width:10.3257%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Бугаївці</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:54.866%;left:57.9047%;width:10.6096%;'>
				<div class='g-aiPstyle3'>Склади поруч </div>
				<div class='g-aiPstyle3'>зі станцією &laquo;Одеса-Західна&raquo;</div>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:66.2236%;left:58.1917%;width:11.7687%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:66.2236%;left:6.8924%;width:8.0503%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:69.1941%;left:0.3379%;width:8.0475%;'>
				<p class='g-aiPstyle5'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:69.3941%;left:56.9789%;width:8.3997%;'>
				<div class='g-aiPstyle6'>20,7</div>
				<div class='g-aiPstyle6'>24,7</div>
				<div class='g-aiPstyle6'>28,7</div>
				<div class='g-aiPstyle6'>32,6</div>
				<div class='g-aiPstyle6'>36,6</div>
				<div class='g-aiPstyle6'>40,6</div>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:69.3941%;left:10.1596%;width:2.7536%;'>
				<div class='g-aiPstyle6'>0,89</div>
				<div class='g-aiPstyle6'>0,70</div>
				<div class='g-aiPstyle6'>0,52</div>
				<div class='g-aiPstyle6'>0,33</div>
				<div class='g-aiPstyle6'>0,15</div>
				<div class='g-aiPstyle6'>-0,04</div>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:91.9093%;left:95.7212%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-16' class='g-Layer_1 g-aiAbs' style='top:94.3556%;right:1.0128%;width:16.2431%;'>
				<p class='g-aiPstyle8'>Дані: Landsat 8, OpenStreetMap</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-01 - 21:25 -->
</div>`


var dniproMaps = `<div id='g-dnipro-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-01 - 23:41 -->
	<!-- ai file: dnipro -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-dnipro-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='950'>
		<style type='text/css' media='screen,print'>
			#g-dnipro-Artboard_1{
				position:relative;
				overflow:hidden;
				width:950px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-dnipro-Artboard_1 p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle0 {
				font-size:21px;
				line-height:25px;
				text-align:center;
				color:#3a3f4a;
				font-weight: bold;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle1 {
				font-size:14px;
				line-height:17px;
				color:#C2C2C2;
				font-weight: 300;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#3a3f4a;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle4 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle5 {
				font-size:11px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle6 {
				font-size:10px;
				line-height:13px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-dnipro-Artboard_1 .g-aiPstyle7 {
				font-size:10px;
				line-height:12px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-dnipro-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/dnipro-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:1.6601%;left:78.4096%;width:50.5818%;margin-left:-25.2909%;'>
				<p class='g-aiPstyle0'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:1.6601%;left:24.2059%;width:50.5818%;margin-left:-25.2909%;'>
				<p class='g-aiPstyle0'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:3.9428%;left:0.3271%;width:7.6241%;'>
				<div class='g-aiPstyle1'>ДНІПРО</div>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:7.8856%;left:23.7721%;width:37.8078%;margin-left:-18.9039%;'>
				<div class='g-aiPstyle2'>(середнє значення за 7 та 23 серпня 2015 року, </div>
				<div class='g-aiPstyle2'>30 м на піксель)</div>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:8.0931%;left:77.9463%;width:37.0171%;margin-left:-18.5085%;'>
				<div class='g-aiPstyle2'>(середнє значення за 7 та 23 серпня 2015 року,</div>
				<div class='g-aiPstyle2'>100 м на піксель)</div>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:24.6942%;left:88.4203%;width:10.4591%;'>
				<div class='g-aiPstyle3'>Епіцентр спеки в Індустріальному районі</div>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:73.6676%;left:55.3389%;width:11.7687%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:73.6676%;left:6.6712%;width:8.0503%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:77.4029%;left:0.3167%;width:8.0475%;'>
				<p class='g-aiPstyle5'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:77.4029%;right:87.729%;width:2.7536%;'>
				<div class='g-aiPstyle6'>0,91</div>
				<div class='g-aiPstyle6'>0,72</div>
				<div class='g-aiPstyle6'>0,53</div>
				<div class='g-aiPstyle6'>0,34</div>
				<div class='g-aiPstyle6'>0,15</div>
				<div class='g-aiPstyle6'>-0,05</div>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:77.6104%;right:37.1938%;width:2.7854%;'>
				<div class='g-aiPstyle6'>21,7</div>
				<div class='g-aiPstyle6'>25,6</div>
				<div class='g-aiPstyle6'>29,3</div>
				<div class='g-aiPstyle6'>33,1</div>
				<div class='g-aiPstyle6'>37,5</div>
				<div class='g-aiPstyle6'>42,2</div>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:91.0989%;right:0.5457%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:94.0041%;right:0.6316%;width:16.2431%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, OpenStreetMap</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-01 - 23:41 -->
</div>`



var lvivMaps = `<div id='g-lviv-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 09:47 -->
	<!-- ai file: lviv -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-lviv-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='950'>
		<style type='text/css' media='screen,print'>
			#g-lviv-Artboard_1{
				position:relative;
				overflow:hidden;
				width:950px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-lviv-Artboard_1 p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-lviv-Artboard_1 .g-aiPstyle0 {
				font-size:21px;
				line-height:25px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-lviv-Artboard_1 .g-aiPstyle1 {
				font-size:14px;
				line-height:17px;
				color:#C2C2C2;
				font-weight: 300;
			}
			#g-lviv-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-lviv-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#3a3f4a;
			}
			#g-lviv-Artboard_1 .g-aiPstyle4 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-lviv-Artboard_1 .g-aiPstyle5 {
				font-size:11px;
				line-height:13px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-lviv-Artboard_1 .g-aiPstyle6 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
			}
			#g-lviv-Artboard_1 .g-aiPstyle7 {
				font-size:10px;
				line-height:12px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-lviv-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/lviv-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:1.6327%;left:77.4244%;width:50.5819%;margin-left:-25.291%;'>
				<p class='g-aiPstyle0'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:1.8367%;left:24.4417%;width:50.5818%;margin-left:-25.2909%;'>
				<p class='g-aiPstyle0'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:3.2653%;left:0.2735%;width:7.6241%;'>
				<div class='g-aiPstyle1'>ЛЬВІВ</div>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:7.9592%;left:24.0078%;width:37.8078%;margin-left:-18.9039%;'>
				<div class='g-aiPstyle2'>(середнє значення за 8 та 24 серпня 2015 року, </div>
				<div class='g-aiPstyle2'>30 м на піксель)</div>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:7.9592%;left:77.3064%;width:57.3026%;margin-left:-28.6513%;'>
				<div class='g-aiPstyle2'>(середнє значення за 8 та 24 серпня 2015 року,</div>
				<div class='g-aiPstyle2'>100 м на піксель)</div>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:31.0204%;left:88.5908%;width:10.4592%;'>
				<div class='g-aiPstyle3'>Епіцентр спеки</div>
				<div class='g-aiPstyle3'>у центральній частині міста та на Замарстинові</div>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:37.1429%;left:54.9418%;width:10.4592%;'>
				<div class='g-aiPstyle3'>Індустріальний</div>
				<div class='g-aiPstyle3'>район поруч з </div>
				<div class='g-aiPstyle3'>Рясним</div>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:58.1633%;left:0.6822%;width:11.0781%;'>
				<div class='g-aiPstyle3'>Чи не єдина зелена пляма в центрі міста &mdash; парк ім. І. Франка</div>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:58.0918%;left:55.1409%;width:6.5912%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки в районі Левандівки</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:72.6531%;left:55.0483%;width:11.7687%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:72.6531%;left:7.328%;width:8.0503%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:76.3265%;right:37.7822%;width:3.6735%;'>
				<div class='g-aiPstyle5'>16,2</div>
				<div class='g-aiPstyle5'>19,8</div>
				<div class='g-aiPstyle5'>23,4</div>
				<div class='g-aiPstyle5'>27,0</div>
				<div class='g-aiPstyle5'>30,6</div>
				<div class='g-aiPstyle5'>34,2</div>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:76.3265%;left:0.6472%;width:8.0475%;'>
				<p class='g-aiPstyle6'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:76.3265%;right:86.878%;width:3.3689%;'>
				<div class='g-aiPstyle5'>0,88</div>
				<div class='g-aiPstyle5'>0,70</div>
				<div class='g-aiPstyle5'>0,52</div>
				<div class='g-aiPstyle5'>0,34</div>
				<div class='g-aiPstyle5'>0,17</div>
				<div class='g-aiPstyle5'>-0,01</div>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:92.8571%;right:1.2375%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-16' class='g-Layer_1 g-aiAbs' style='top:95.9184%;right:1.0526%;width:16.243%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, OpenStreetMap</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 09:47 -->
</div>`


var kharkivMaps = `<div id='g-kharkiv-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 10:09 -->
	<!-- ai file: kharkiv -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-kharkiv-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='950'>
		<style type='text/css' media='screen,print'>
			#g-kharkiv-Artboard_1{
				position:relative;
				overflow:hidden;
				width:950px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-kharkiv-Artboard_1 p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle0 {
				font-size:21px;
				line-height:25px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle1 {
				font-size:14px;
				line-height:17px;
				color:#C2C2C2;
				font-weight: 300;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#3a3f4a;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle4 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle5 {
				font-size:11px;
				line-height:13px;
				color:#3a3f4a;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle6 {
				font-size:10px;
				line-height:13px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-kharkiv-Artboard_1 .g-aiPstyle7 {
				font-size:10px;
				line-height:12px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-kharkiv-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/kharkiv-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:1.6856%;left:77.0603%;width:50.5819%;margin-left:-25.291%;'>
				<p class='g-aiPstyle0'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:1.6856%;left:24.3933%;width:50.5818%;margin-left:-25.2909%;'>
				<p class='g-aiPstyle0'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:2.622%;left:0.304%;width:7.6241%;'>
				<div class='g-aiPstyle1'>ХАРКІВ</div>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:7.3042%;left:23.9595%;width:37.8078%;margin-left:-18.9039%;'>
				<div class='g-aiPstyle2'>(середнє значення за 4 червня та 6 липня 2015 року, </div>
				<div class='g-aiPstyle2'>30 м на піксель)</div>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:7.4915%;left:76.9423%;width:57.3026%;margin-left:-28.6513%;'>
				<div class='g-aiPstyle2'>(середнє значення за 4 червня та 6 липня 2015 року,</div>
				<div class='g-aiPstyle2'>100 м на піксель)</div>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:24.16%;left:55.6603%;width:8.8435%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Горчарівці та Москалівці</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:31.4642%;left:35.9083%;width:11.1701%;'>
				<p class='g-aiPstyle3'>Острівець прохолоди в центрі міста &mdash; парк Шевченка</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:42.7015%;left:89.8352%;width:11.1069%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки </p>
				<p class='g-aiPstyle3'>на Балашівці</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:76.4132%;left:55.1263%;width:11.7688%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:76.4132%;left:7.0691%;width:8.0503%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:79.4098%;left:0.3883%;width:8.0475%;'>
				<p class='g-aiPstyle5'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:79.597%;right:87.3311%;width:2.7536%;'>
				<div class='g-aiPstyle6'>0,91</div>
				<div class='g-aiPstyle6'>0,69</div>
				<div class='g-aiPstyle6'>0,47</div>
				<div class='g-aiPstyle6'>0,25</div>
				<div class='g-aiPstyle6'>0,03</div>
				<div class='g-aiPstyle6'>-0,20</div>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:79.597%;right:37.8604%;width:3.8597%;'>
				<div class='g-aiPstyle6'>23,1</div>
				<div class='g-aiPstyle6'>26,6</div>
				<div class='g-aiPstyle6'>30,0</div>
				<div class='g-aiPstyle6'>33,5</div>
				<div class='g-aiPstyle6'>37,0</div>
				<div class='g-aiPstyle6'>40,4</div>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:94.2054%;right:0.5081%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:97.0147%;right:0.5263%;width:27.5679%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, Міністерство регіонального розвитку</p>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 10:09 -->
</div>`


var kyivMapsMob = `<div id='g-kyiv-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 18:37 -->
	<!-- ai file: kyiv-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-kyiv-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-kyiv-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-kyiv-mob-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle0 {
				font-size:10px;
				line-height:12px;
				text-align:center;
				color:#999999;
				font-weight:300;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle1 {
				font-size:16px;
				line-height:19px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle2 {
				font-size:12px;
				line-height:14px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle3 {
				font-size:10px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle4 {
				font-size:9px;
				line-height:11px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle5 {
				font-size:9px;
				line-height:9px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle6 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
			}
			#g-kyiv-mob-Artboard_1 .g-aiPstyle7 {
				font-size:9px;
				line-height:11px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-kyiv-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/kyiv-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:1.1395%;left:49.8892%;width:7.7783%;margin-left:-3.8892%;'>
				<p class='g-aiPstyle0'>КИЇВ</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:3.2918%;left:51.0897%;width:129.7425%;margin-left:-64.8713%;'>
				<p class='g-aiPstyle1'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:5.9506%;left:50.0002%;width:90.8831%;margin-left:-45.4416%;'>
				<p class='g-aiPstyle2'>(середнє значення за 13 та 29 липня 2016 року, 30 м на піксель)</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:33.678%;left:3.478%;width:32.4811%;'>
				<p class='g-aiPstyle3'>NDVI (Нормалізований відносний індекс рослинності) &mdash; показник кількості активної фотосинтетичної  біомаси </p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:36.8432%;left:75.8405%;width:22.5189%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:38.869%;right:1.5%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,93</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:38.9956%;left:69.5052%;width:16.513%;'>
				<p class='g-aiPstyle6'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:40.1351%;right:1.5%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,73</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:41.4012%;right:1.5%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,52</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:42.7939%;right:1.5%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,32</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:44.0599%;right:1.5%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,16</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:45.1994%;right:1.5%;width:8.112%;'>
				<p class='g-aiPstyle5'>-0,09</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:52.796%;left:49%;width:88%;margin-left:-44%;'>
				<p class='g-aiPstyle1'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:55.708%;left:49.0578%;width:90.3271%;margin-left:-45.1636%;'>
				<p class='g-aiPstyle2'>(середнє значення за 13 та 29 липня 2016 року,</p>
				<p class='g-aiPstyle2'>100 м на піксель)</p>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:80.0169%;left:9.9583%;width:18.1471%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Оболоні</p>
			</div>
			<div id='g-ai0-16' class='g-Layer_1 g-aiAbs' style='top:86.7272%;left:71.9967%;width:25.3789%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Позняках, Березняках і Воскресенці</p>
			</div>
			<div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:87.8667%;left:8.2243%;width:28.7757%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:89.7658%;right:73.4627%;width:7.7293%;'>
				<p class='g-aiPstyle5'>23,7</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:91.1585%;right:73.4627%;width:7.7293%;'>
				<p class='g-aiPstyle5'>27,0</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:92.298%;right:73.4627%;width:7.7293%;'>
				<p class='g-aiPstyle5'>30,4</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:93.6907%;right:73.4627%;width:7.7293%;'>
				<p class='g-aiPstyle5'>34,8</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-22' class='g-Layer_1 g-aiAbs' style='top:94.9568%;right:73.4627%;width:7.7293%;'>
				<p class='g-aiPstyle5'>40,1</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-23' class='g-Layer_1 g-aiAbs' style='top:96.2229%;right:73.4627%;width:7.7293%;'>
				<p class='g-aiPstyle5'>45,5</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-24' class='g-Layer_1 g-aiAbs' style='top:96.3495%;right:2.4492%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-25' class='g-Layer_1 g-aiAbs' style='top:97.8688%;right:2.291%;width:48.4678%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, OpenStreetMap</p>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 18:37 -->
</div>`


var odesaMapsMob = `<div id='g-odesa-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 21:33 -->
	<!-- ai file: odesa-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-odesa-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-odesa-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-odesa-mob-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle0 {
				font-size:10px;
				line-height:12px;
				color:#999999;
				font-weight:300;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle1 {
				font-size:16px;
				line-height:19px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle2 {
				font-size:12px;
				line-height:14px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle3 {
				font-size:10px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle4 {
				font-size:9px;
				line-height:11px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle5 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle6 {
				font-size:9px;
				line-height:9px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-odesa-mob-Artboard_1 .g-aiPstyle7 {
				font-size:9px;
				line-height:11px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-odesa-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/odesa-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:0%;left:43.7778%;width:17.383%;'>
				<p class='g-aiPstyle0'>ОДЕСА</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:2.1723%;left:50.6749%;width:83.0838%;margin-left:-41.5419%;'>
				<p class='g-aiPstyle1'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:4.5732%;left:50.3456%;width:87.0314%;margin-left:-43.5157%;'>
				<p class='g-aiPstyle2'>(середнє значення за 20 липня та 5 серпня 2015 року, 30 м на піксель)</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:17.721%;left:3.9668%;width:30.7816%;'>
				<p class='g-aiPstyle3'>Преображенський парк в центрі міста</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:20.9222%;left:73.875%;width:19.7923%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:22.2942%;left:60.9541%;width:18.348%;'>
				<p class='g-aiPstyle5'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:22.4085%;right:8.8695%;width:9.5283%;'>
				<p class='g-aiPstyle6'>0,89</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:23.5518%;right:8.8695%;width:9.5283%;'>
				<p class='g-aiPstyle6'>0,70</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:24.6951%;right:8.8695%;width:9.5283%;'>
				<p class='g-aiPstyle6'>0,52</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:25.8384%;right:8.8695%;width:9.5283%;'>
				<p class='g-aiPstyle6'>0,33</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:26.9817%;right:8.8695%;width:9.5283%;'>
				<p class='g-aiPstyle6'>0,15</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:28.125%;right:8.8695%;width:9.5283%;'>
				<p class='g-aiPstyle6'>-0,04</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:54.3064%;left:48.4465%;width:80.1603%;margin-left:-40.0802%;'>
				<p class='g-aiPstyle1'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:56.7073%;left:50.5735%;width:84.4142%;margin-left:-42.2071%;'>
				<p class='g-aiPstyle2'>(середнє значення 20 липня та 5 серпня 2015 року, 100 м на піксель)</p>
			</div>
			<div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:64.596%;left:18.1662%;width:26.959%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки у Суворовському районі</p>
			</div>
			<div id='g-ai0-16' class='g-Layer_1 g-aiAbs' style='top:72.3704%;left:3.8817%;width:27.764%;'>
				<p class='g-aiPstyle3'>Склади поруч </p>
				<p class='g-aiPstyle3'>зі станцією &laquo;Одеса-Західна&raquo;</p>
			</div>
			<div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:73.3994%;left:65.3955%;width:23.5426%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Бугаївці</p>
			</div>
			<div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:81.7454%;left:68.3385%;width:26.8327%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:83.4603%;right:13.3333%;width:9.3021%;'>
				<p class='g-aiPstyle6'>20,7</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:84.6036%;right:13.3333%;width:9.3021%;'>
				<p class='g-aiPstyle6'>24,7</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:85.7469%;right:13.3333%;width:9.3021%;'>
				<p class='g-aiPstyle6'>28,7</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-22' class='g-Layer_1 g-aiAbs' style='top:86.8902%;right:13.3333%;width:9.3021%;'>
				<p class='g-aiPstyle6'>32,6</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-23' class='g-Layer_1 g-aiAbs' style='top:88.0335%;right:13.3333%;width:9.3021%;'>
				<p class='g-aiPstyle6'>36,6</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-24' class='g-Layer_1 g-aiAbs' style='top:89.1768%;right:13.3333%;width:9.3021%;'>
				<p class='g-aiPstyle6'>40,6</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-25' class='g-Layer_1 g-aiAbs' style='top:96.4939%;right:2.5941%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-26' class='g-Layer_1 g-aiAbs' style='top:97.8658%;right:2.1478%;width:47.0745%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, OpenStreetMap</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 21:33 -->
</div>`


var dniproMapsMob = `<div id='g-dnipro-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 20:44 -->
	<!-- ai file: dnipro-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-dnipro-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-dnipro-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-dnipro-mob-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle0 {
				font-size:10px;
				line-height:12px;
				color:#999999;
				font-weight:300;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle1 {
				font-size:16px;
				line-height:19px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle2 {
				font-size:12px;
				line-height:14px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle3 {
				font-size:9px;
				line-height:11px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle4 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle5 {
				font-size:9px;
				line-height:9px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle6 {
				font-size:10px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-dnipro-mob-Artboard_1 .g-aiPstyle7 {
				font-size:9px;
				line-height:11px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-dnipro-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/dnipro-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-ai2html-settings g-aiAbs' style='top:0%;left:41.3086%;width:17.3828%;'>
				<p class='g-aiPstyle0'>ДНІПРО</p>
			</div>
			<div id='g-ai0-2' class='g-ai2html-settings g-aiAbs' style='top:2.697%;left:49.938%;width:99.876%;margin-left:-49.938%;'>
				<p class='g-aiPstyle1'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-ai2html-settings g-aiAbs' style='top:5.678%;left:50.2557%;width:89.2021%;margin-left:-44.6011%;'>
				<p class='g-aiPstyle2'>(середнє значення за 7 та 23 серпня 2015 року, </p>
				<p class='g-aiPstyle2'>30 м на піксель)</p>
			</div>
			<div id='g-ai0-4' class='g-ai2html-settings g-aiAbs' style='top:35.7712%;left:18.599%;width:19.8545%;'>
				<p class='g-aiPstyle3'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-5' class='g-ai2html-settings g-aiAbs' style='top:37.6166%;left:2.0666%;width:18.3483%;'>
				<p class='g-aiPstyle4'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:37.7585%;right:65.293%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,91</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:39.178%;right:65.293%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,72</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:40.5975%;right:65.293%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,53</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:42.017%;right:65.293%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,34</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:43.4365%;right:65.293%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,15</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:44.856%;right:65.293%;width:9.5283%;'>
				<p class='g-aiPstyle5'>-0,05</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-12' class='g-ai2html-settings g-aiAbs' style='top:54.0827%;left:50.4979%;width:100.9958%;margin-left:-50.4979%;'>
				<p class='g-aiPstyle1'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-13' class='g-ai2html-settings g-aiAbs' style='top:57.2056%;left:49.1731%;width:89.0366%;margin-left:-44.5183%;'>
				<p class='g-aiPstyle2'>(середнє значення за 7 та 23 серпня 2015 року,</p>
				<p class='g-aiPstyle2'>100 м на піксель)</p>
			</div>
			<div id='g-ai0-14' class='g-ai2html-settings g-aiAbs' style='top:62.5255%;left:69.5928%;width:29.9661%;'>
				<p class='g-aiPstyle6'>Епіцентр спеки в Індустріальному районі</p>
			</div>
			<div id='g-ai0-16' class='g-ai2html-settings g-aiAbs' style='top:86.5891%;left:4.6426%;width:26.8327%;'>
				<p class='g-aiPstyle3'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:88.5764%;right:78.3333%;width:9.3021%;'>
				<p class='g-aiPstyle5'>21,7</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:89.9959%;right:78.3333%;width:9.3021%;'>
				<p class='g-aiPstyle5'>25,6</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:91.4154%;right:78.3333%;width:9.3021%;'>
				<p class='g-aiPstyle5'>29,2</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:92.8349%;right:78.3333%;width:9.3021%;'>
				<p class='g-aiPstyle5'>33,1</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:94.2544%;right:78.3333%;width:9.3021%;'>
				<p class='g-aiPstyle5'>37,5</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-22' class='g-Layer_1 g-aiAbs' style='top:95.6739%;right:78.3333%;width:9.3021%;'>
				<p class='g-aiPstyle5'>42,2</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-23' class='g-ai2html-settings g-aiAbs' style='top:95.9319%;right:1.7744%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-24' class='g-ai2html-settings g-aiAbs' style='top:97.7353%;right:1.3079%;width:50.5254%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, OpenStreetMap</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 20:44 -->
</div>`


var lvivMapsMob = `<div id='g-lviv-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 21:04 -->
	<!-- ai file: lviv-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-lviv-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-lviv-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-lviv-mob-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle0 {
				font-size:10px;
				line-height:12px;
				text-align:center;
				color:#999999;
				font-weight:300;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle1 {
				font-size:16px;
				line-height:19px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle2 {
				font-size:12px;
				line-height:14px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle3 {
				font-size:10px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle4 {
				font-size:9px;
				line-height:11px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle5 {
				font-size:9px;
				line-height:9px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle6 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
			}
			#g-lviv-mob-Artboard_1 .g-aiPstyle7 {
				font-size:9px;
				line-height:11px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-lviv-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/lviv-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-ai2html-settings g-aiAbs' style='top:0.1305%;left:50.1665%;width:14.238%;margin-left:-7.119%;'>
				<p class='g-aiPstyle0'>ЛЬВІВ</p>
			</div>
			<div id='g-ai0-2' class='g-ai2html-settings g-aiAbs' style='top:2.4786%;left:50.1772%;width:100.2153%;margin-left:-50.1077%;'>
				<p class='g-aiPstyle1'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-ai2html-settings g-aiAbs' style='top:5.3485%;left:48.6639%;width:90.1071%;margin-left:-45.0535%;'>
				<p class='g-aiPstyle2'>(середнє значення за 8 та 24 серпня 2015 року, </p>
				<p class='g-aiPstyle2'>30 м на піксель)</p>
			</div>
			<div id='g-ai0-4' class='g-ai2html-settings g-aiAbs' style='top:13.8277%;left:63.8958%;width:31.0964%;'>
				<p class='g-aiPstyle3'>Чи не єдина зелена пляма в центрі міста &mdash;</p>
				<p class='g-aiPstyle3'>парк ім. І. Франка</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:39.396%;left:15.5417%;width:19.7923%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:41.0919%;right:67.2028%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,88</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-7' class='g-ai2html-settings g-aiAbs' style='top:41.0919%;left:2.0208%;width:18.3483%;'>
				<p class='g-aiPstyle6'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:42.3964%;right:67.2028%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,70</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:43.7009%;right:67.2028%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,52</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:45.0054%;right:67.2028%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,34</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:46.3099%;right:67.2028%;width:9.5283%;'>
				<p class='g-aiPstyle5'>0,17</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:47.6144%;right:67.2028%;width:9.5283%;'>
				<p class='g-aiPstyle5'>-0,01</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-13' class='g-ai2html-settings g-aiAbs' style='top:53.4846%;left:49.227%;width:115.3267%;margin-left:-57.6633%;'>
				<p class='g-aiPstyle1'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-14' class='g-ai2html-settings g-aiAbs' style='top:56.3545%;left:49.6416%;width:99.2832%;margin-left:-49.6416%;'>
				<p class='g-aiPstyle2'>(середнє значення за 8 та 24 серпня 2015 року,</p>
				<p class='g-aiPstyle2'>100 м на піксель)</p>
			</div>
			<div id='g-ai0-15' class='g-ai2html-settings g-aiAbs' style='top:62.6162%;left:67.8594%;width:28.8073%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки </p>
				<p class='g-aiPstyle3'>у центральній частині міста та на Замарстинові</p>
			</div>
			<div id='g-ai0-16' class='g-ai2html-settings g-aiAbs' style='top:84.0536%;left:2.2542%;width:27.1584%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки в районі Левандівки</p>
			</div>
			<div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:89.3585%;left:5.0052%;width:26.8327%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:91.3152%;right:76.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>16,2</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:92.6197%;right:76.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>19,8</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:93.9242%;right:76.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>23,4</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:95.2288%;right:76.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>27,0</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-22' class='g-ai2html-settings g-aiAbs' style='top:96.0115%;right:2.1217%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-23' class='g-Layer_1 g-aiAbs' style='top:96.5333%;right:76.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>30,6</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-24' class='g-ai2html-settings g-aiAbs' style='top:97.7073%;right:1.7005%;width:50.2995%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, OpenStreetMap</p>
			</div>
			<div id='g-ai0-25' class='g-Layer_1 g-aiAbs' style='top:97.8378%;right:76.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>34,2</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 21:04 -->
</div>`


var kharkivMapsMob = `<div id='g-kharkiv-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.60 - 2017-05-02 - 21:26 -->
	<!-- ai file: kharkiv-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-kharkiv-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-kharkiv-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-kharkiv-mob-Artboard_1 p{
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle0 {
				font-size:10px;
				line-height:12px;
				text-align:center;
				color:#999999;
				font-weight:300;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle1 {
				font-size:16px;
				line-height:19px;
				text-align:center;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle2 {
				font-size:12px;
				line-height:14px;
				text-align:center;
				color:#3a3f4a;
				font-weight:300;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle3 {
				font-size:10px;
				line-height:12px;
				color:#3a3f4a;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle4 {
				font-size:9px;
				line-height:11px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle5 {
				font-size:9px;
				line-height:9px;
				text-align:right;
				color:#3a3f4a;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle6 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
			}
			#g-kharkiv-mob-Artboard_1 .g-aiPstyle7 {
				font-size:9px;
				line-height:11px;
				text-align:right;
				color:#999999;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-kharkiv-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/kharkiv-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-ai2html-settings g-aiAbs' style='top:0.1179%;left:50.276%;width:17.3828%;margin-left:-8.6914%;'>
				<p class='g-aiPstyle0'>ХАРКІВ</p>
			</div>
			<div id='g-ai0-2' class='g-ai2html-settings g-aiAbs' style='top:2.2401%;left:50%;width:100%;margin-left:-50%;'>
				<p class='g-aiPstyle1'>Індекс рослинності (NDVI)</p>
			</div>
			<div id='g-ai0-3' class='g-ai2html-settings g-aiAbs' style='top:4.834%;left:50.2847%;width:101.236%;margin-left:-50.618%;'>
				<p class='g-aiPstyle2'>(середнє значення за 4 червня та 6 липня 2015 року, </p>
				<p class='g-aiPstyle2'>30 м на піксель)</p>
			</div>
			<div id='g-ai0-4' class='g-ai2html-settings g-aiAbs' style='top:10.1395%;left:71.377%;width:25.4674%;'>
				<p class='g-aiPstyle3'>Острівець прохолоди в центрі міста &mdash; парк Шевченка</p>
			</div>
			<div id='g-ai0-5' class='g-ai2html-settings g-aiAbs' style='top:38.7895%;left:64.1738%;width:22.5189%;'>
				<p class='g-aiPstyle4'>Індекс NDVI</p>
			</div>
			<div id='g-ai0-6' class='g-ai2html-settings g-aiAbs' style='top:40.5581%;right:13.1667%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,91</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-7' class='g-ai2html-settings g-aiAbs' style='top:40.676%;left:55.9274%;width:18.348%;'>
				<p class='g-aiPstyle6'>здорова рослинність (ліси, парки) </p>
			</div>
			<div id='g-ai0-8' class='g-ai2html-settings g-aiAbs' style='top:41.7371%;right:13.1667%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,69</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-9' class='g-ai2html-settings g-aiAbs' style='top:42.9161%;right:13.1667%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,47</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-10' class='g-ai2html-settings g-aiAbs' style='top:44.213%;right:13.1667%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,25</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-11' class='g-ai2html-settings g-aiAbs' style='top:45.392%;right:13.1667%;width:8.112%;'>
				<p class='g-aiPstyle5'>0,03</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-12' class='g-ai2html-settings g-aiAbs' style='top:46.4531%;right:13.1667%;width:8.112%;'>
				<p class='g-aiPstyle5'>-0,20</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-13' class='g-ai2html-settings g-aiAbs' style='top:53.5272%;left:50.2946%;width:100.5892%;margin-left:-50.2946%;'>
				<p class='g-aiPstyle1'>Температура поверхні, °C;</p>
			</div>
			<div id='g-ai0-14' class='g-ai2html-settings g-aiAbs' style='top:56.2389%;left:50.1643%;width:100.5724%;margin-left:-50.2862%;'>
				<p class='g-aiPstyle2'>(середнє значення за 4 червня та 6 липня 2015 року,</p>
				<p class='g-aiPstyle2'>100 м на піксель)</p>
			</div>
			<div id='g-ai0-15' class='g-ai2html-settings g-aiAbs' style='top:60.0118%;left:2.0378%;width:23.3696%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки на Горчарівці та Москалівці</p>
			</div>
			<div id='g-ai0-16' class='g-ai2html-settings g-aiAbs' style='top:72.6272%;left:73.932%;width:25.3239%;'>
				<p class='g-aiPstyle3'>Епіцентр спеки </p>
				<p class='g-aiPstyle3'>на Балашівці</p>
			</div>
			<div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:89.0155%;left:2.0052%;width:26.8327%;'>
				<p class='g-aiPstyle4'>Градуси Цельсія</p>
			</div>
			<div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:90.784%;right:79.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>23,1</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:91.963%;right:79.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>26,6</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:93.142%;right:79.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>30,0</p>
			</div>
			<div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:94.321%;right:79.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>33,5</p>
			</div>
			<div id='g-ai0-22' class='g-Layer_1 g-aiAbs' style='top:95.5001%;right:79.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>37,0</p>
			</div>
			<div id='g-ai0-23' class='g-ai2html-settings g-aiAbs' style='top:95.7359%;right:2.7171%;'>
				<p class='g-aiPstyle7'>2,5 км</p>
			</div>
			<div id='g-ai0-24' class='g-Layer_1 g-aiAbs' style='top:96.6791%;right:79.6667%;width:9.3021%;'>
				<p class='g-aiPstyle5'>40,4</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-25' class='g-ai2html-settings g-aiAbs' style='top:97.2686%;right:2.7588%;width:52.8551%;'>
				<p class='g-aiPstyle7'>Дані: Landsat 8, Міністерство регіонального розвитку</p>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-05-02 - 21:26 -->
</div>`

$("#kyiv").append(kyivMaps);
$("#kyivMob").append(kyivMapsMob);

$("#odesa").append(odesaMaps);
$("#odesaMob").append(odesaMapsMob);

$("#dnipro").append(dniproMaps);
$("#dniproMob").append(dniproMapsMob);

$("#lviv").append(lvivMaps);
$("#lvivMob").append(lvivMapsMob);

$("#kharkiv").append(kharkivMaps);
$("#kharkivMob").append(kharkivMapsMob);




